var motorCycle = "Motorcycle";
console.log("Is motorCycle == Motorcycle? I predict True");
console.log(motorCycle == "Motorcycle");
var bike = "Bike";
console.log("Is bike == Bike? I predict True");
console.log(bike == "Bike");
var car = "Container";
console.log("Is car == Car? I predict False");
console.log(car == "Car");
var container = "Car";
console.log("Is container == Container? I predict false");
console.log(container == "Container");
var truck = "Range Rover";
console.log("Is truck == Truck? I predict False");
console.log(truck == "Truck");
var rangeRover = "Range Rover";
console.log("Is rangRover == Range Rover? I predict True");
console.log(rangeRover == "Range Rover");
var cycle = "Cycle";
console.log("Is cycle == Cycle? I predict True");
console.log(cycle == "Cycle");
var wheelChair = "Wheel Chair";
console.log("Is wheelChair == Wheel Chair? I predict True");
console.log(wheelChair == "Wheel Chair");
var redLight = "Green Light";
console.log("Is redLight == Red Light? I predict False");
console.log(redLight == "Red Light");
var greenLight = "Red Light";
console.log("Is greenLight == Green Light? I predict False");
console.log(greenLight == "Green Light");
