"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var name1 = "Huzair";
var name2 = "Huzaifa";
console.log("Equality check =", name1 == name2);
console.log("Inequality check =", name1 != name2);
var newName = name1.toLocaleLowerCase();
console.log("LowerCase Check =", newName == name1);
var num1 = 2;
var num2 = 10;
console.log("Numeric equality check = ", num1 == num2);
console.log("Numberic inequality check = ", num1 != num2);
console.log("Greater Than check = ", num1 > num2);
console.log('Less Than check = ', num1 < num2);
console.log("Greater Than or equals to check = ", num1 >= num2);
console.log("Less Than or equals to check = ", num1 <= num2);
console.log(num1 && num2);
console.log(num1 || num2);
var myArr = [1, 2, 3, 4, 5];
var newArr = [6];
console.log(myArr[4]);
console.log(!myArr[5]);
